apiVersion: sources.knative.dev/v1alpha1
kind: PingSource
metadata:
  name: ergast-importer-cronjob-source
spec:
  schedule: "*/2 * * * *"
  data: '{"message": "Start processing now!"}'
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: ergast-importer